<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by id
     */
    function login($params)
    {
        return $this->db->get_where('users',$params)->row_array();
    }

    function get_user($id)
    {
        return $this->db->get_where('users',array('id'=>$id))->row_array();
    }

    function get_user_email($email)
    {
        return $this->db->get_where('users',array('email'=>$email))->row_array();
    }
    
    /*
     * Get all users count
     */
    function get_all_users_count()
    {
        $this->db->from('users');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all users
     */
    function get_all_users($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        // $this->db->where('site_id', $_SESSION['site_id']);
        // if ($this->session->userdata('role') == SITE_MANAGER)
        // {
        //     $this->db->where('role', THERAPIST);
        //     $this->db->or_where('role', PRP_WORKER);
        // }
        // if ($this->session->userdata('role') == ADMIN)
        // {
        //     $this->db->where('role', ADMIN);
        //     $this->db->or_where('role', SITE_MANAGER);
        // }
        return $this->db->get('users')->result_array();
    }

    function get_all_search_users($value)
    {
        $this->db->order_by('id', 'desc');
        if ($this->session->userdata('role') == SITE_MANAGER)
        {
            $this->db->where('role', THERAPIST);
            $this->db->or_where('role', PRP_WORKER);
        }
        $this->db->like('first_name', $value);
        $this->db->or_like('last_name', $value);
        return $this->db->get('users')->result_array();
    }
        
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('users',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($id)
    {
        return $this->db->delete('users',array('id'=>$id));
    }
}
